### ISSUE TITLE
No USB connection / devices are not discovered

### ISSUE THREAD

**Issue by 0anton** [z8i/ha_custom_klimaloggpro#2]
I've installed the ha_custom_klimaloggpro extension into "Home Assistant 2022.4.5", installation type "Home Assitant OS" with the help of HACS

I've connected the USB stick and see it appears in the list of devices under dev id 6666:5555:

```
[core-ssh ~]$ lsusb
Bus 001 Device 005: ID 10c4:ea60
Bus 001 Device 001: ID 1d6b:0002
Bus 001 Device 003: ID 0424:ec00
Bus 001 Device 002: ID 0424:9514
Bus 001 Device 007: ID 6666:5555
```

The device is readable by the root user:
```
[core-ssh ~]$ ls -l /dev/bus/usb/001/007
crw-rw-r--    1 root     root      189,   6 Apr 20 23:25 /dev/bus/usb/001/007
```

(I don't now however which user is used to run integraton).

My USB stick is paired with the KlimaLogPro station and can successfully transfer data over windows application.

However, when I plug the stick into Home Assitant, the KlimaLog integration is not able to detect sensors. I tried rebooting assitant, pressing "USB" button on the KlimaLogPro central station (USB symbol blinks indicating that the connection cannot be established).

I don't have any further ideas how to troubleshoot this situation.
I see that some users report that the integration works perfectly for them.

**Comment by hifihifi** [comment]
Here too, I don"t see an exisiting group "plugdev" in the file group.
I use Raspberry Pi 4 with Home assist 2022.6.2
![image](https://user-images.githubusercontent.com/76747167/172404488-bf06ceb4-b070-4a7d-a3f1-b64b1b1e2742.png)

Can this be related to Home assist verion? Group plugdev is gone? Or do we something wrong?

**Comment by z8i** [comment]
Hi! If you use HAOS, the USB device management stuff is not needed. I've added some more infos about how to install it to the Readme.md. Did you add the ingration itself in Home-Assistant Settings-Integrations?

**Comment by hifihifi** [comment]
z8i: I used HAOS clean install on a Raspberry Pi 4 B 8GB with no succes.
I then installed the container version in Docker on my Synology NAS and this works fine.
Strange that on Rasp HAOS this does not work. Did you used docker on Rasp or not?

**Comment by z8i** [comment]
I am running it currently on a Raspi 4B 8GB with HAOS without any problems.

**Comment by hifihifi** [comment]
Strange, I have 7 sensors and use a fast SD card. Maybe to slow? Synology is faster and works
The sensors are not readed out yet at that point I think.

**Comment by z8i** [comment]
8 sensors with fast SD card, so I expect no problem there. How far in the setup process do you get? Can you add the integration itself?

**Comment by hifihifi** [comment]
I tried again installing it on Raspberry Pi and I managed to install it and found some differences.
At step 5, you cannot find it, even after a reboot. You must do a browser refresh. (I use Firefox)
A more complete manual is:

   1 Add repo to HACS
  2  Install custom integration " TFA KlimaLogg pro BETA" via HACS
  3  Restart Home Assistant
 4   Go to Settings-Integrations in Home Assistant; 
 5   Add Integration "Klimalogg".. this takes a while, please be patient! Do a refresh in your browser if you cannot find  "Klimalogg"
 6   Select the sensors you have connected to you base station
7 Add the integration to your dashboard
8 Press 3 seconds on the USB button on the main TFA station
9   finish!

**Comment by hifihifi** [comment]
Another manual: If you put the TFA USB stick from the one Home assistant to another the Stick is confiuzed and get stuck, you can see that he keep blinking at 100% on the main TFA base. To fix this I reconnected usb stick again with windows pc and take all data out (I took the battery first out, I don't know if this is needed). Then I took the USB TFA stick and put him back in my synology, I then started docker container again and it works again. I had seen a man that was telling also that everytime to get a uptime he must press the USB button, this could be his solution too from getting stuck. Mayb worth telling on the FAQ ?

**Comment by z8i** [comment]
I have seen this 100% blinking too, but I was able to just push the USB-button and the main station connected again.

I'll close this issue for now, as it is solved i think... right?
