### ISSUE TITLE
I would like to try/use this

### ISSUE THREAD

**Issue by richardsg307** [z8i/ha_custom_klimaloggpro#3]
Hi.
I'm running HA on an HP T630 thin client using the generic x86-64 HAOS.
I have had the Klimalogg-Pro for several years now with 2 additional sensors feeding in to the App on my windows PC through the dongle.
I would like to use it directly into HA instead, so your work looked good.
I have downloaded and installed the repository ha_custom_klimaloggpro and restarted but apart from the thing showing up in the HACS screen, I'm not seeing anything else and now I'm not sure what to do.
It looks like I have to also download the kloggpro thing but that's where I get lost.
Any help gratefully received.
I also have a question - To send data to the PC required me to press the USB button on the base station. I would want the base station to update HA in real time with no USB button press. Is that possible even?
Thanks.

**Comment by z8i** [comment]
Hi! I will extend the instructions a bit.. after this.
Installation steps:
1. Add repo to HACS
2. Install custom integration " TFA KlimaLogg pro BETA" via HACS
3. Restart Home Assistant
4. Go to Settings-Integrations in Home Assistant
5. Add Integration "Klimalogg".. this takes a while, please be patient!
6. Select the sensors you have connected to you base station
7. finish!

During step 5 i usually press the USB buttom some times (hold it a bit), until the base station is connected with the raspberry. If you use HAOS all the custom usb device right management stuff is not neccessary. Once the station is connected, you can see the live data in Home Assistant, the connection will stay permanent.

**Comment by richardsg307** [comment]
Thanks.
I've just done the update to the TFA Klimalogg pro BETA.
I still am stuck on step 5. Klimalogg does not appear. Do I need to download it or something?

**Comment by z8i** [comment]
Sometimes you need to clear your browser cache or perform hard-refresh in order for the integration to show up. Can you try it?

**Comment by richardsg307** [comment]
z8i - That did the trick, I'm in. Wow, thanks.

**Comment by z8i** [comment]
Happy to hear that! Nice!
