### ISSUE TITLE
Resource busy....

### ISSUE THREAD

**Issue by gigiblabla** [z8i/ha_custom_klimaloggpro#4]
Good morning,
During installation, in step No. 7 "Add the integration to your dashboard". I see the message "Configuration failed" and in the log file I have the message:

" File "/usr/local/lib/python3.11/site-packages/kloggpro/klimalogg.py", line 2405, in _open_device
     raise NameError(e)
NameError: [Errno 16] Resource busy"
Can you help me please ?

**Comment by z8i** [comment]
Please tell more about your system, are you using hassio on a raspberry, or NAS or something? Maybe something else is using the usb device already?

**Comment by gigiblabla** [comment]
Hello z8i, thank you in advance for your help. I confirm that my system is as follows:
1) I use Home Assistant

     Core 2023.12.3
     Supervisor 2023.11.6
     Operating System 11.2
     User interface 20231208.2

2) on a Raspberry: RPI4 model B with 4Gb memory

3) here is the result of :
Bus 001 Device 001: ID 1d6b:0002 => ???
Bus 001 Device 004: ID 6666:5555 => LA CROSSE TECHNOLOGY "WS-2812N-IT" => USBTRX-10S-868 USB (key)
Bus 001 Device 002: ID 2109:3431 => ???
Bus 002 Device 002: ID 174c:55aa => ???
Bus 002 Device 001: ID 1d6b:0003 => ???
Bus 001 Device 003: ID 0a12:0001 => Dongle bluetooth V5.1 "Yunseity USB-Bluetooth-Adapter"

Thank you again for your help. Gigiblabla

**Comment by z8i** [comment]
Do you use another Weather station? (LA CROSSE?)
Maybe it is in conflict with the TFA model. TFA also uses 6666:5555 for its dongle. Can you try to unplug all other USB devices from the rasbperry, restart and try again?

**Comment by gigiblabla** [comment]
Hello, I was able to resolve the issue by simply adding the user to the plugdev group using the command:

sudo adduser <username> plugdev
		

I also had to install the "Advanced SSH & Web Terminal" add-on to access the terminal within Home Assistant.

Thanks to z8i for the help! Unfortunately, I'm now facing another issue and will need to open a separate issue for that.

Gigiblabla
