### ISSUE TITLE
ALARM settings in Base station

### ISSUE THREAD

**Issue by hifihifi** [z8i/ha_custom_klimaloggpro#5]
If I change the min humidity on the basestation to 20% without USB-stick connected to the Home assistant this stays ok.
When I plugin the USB-stick to the Home assistant. The connection is ok. But the ALARM value for min humidity stays on 99%. This result offcourse in a alarm warning.
How to solve?

**Comment by z8i** [comment]
This happens as far as i know due to low battery of one of the sensors. This must be somewhere in the depths of https://github.com/z8i/kloggpro, which is based on https://github.com/matthewwall/weewx-klimalogg. I was not able to find it, where this is set, maybe you can take a look?

**Comment by z8i** [comment]
I just find something about the clock margins... Maybe it is about clock and not low battery... https://github.com/z8i/kloggpro/blob/88a41a42e32140e89db78831977482bfb45b6e8e/kloggpro/klimalogg.py#L2065

**Comment by hifihifi** [comment]
It is not a time alarm but a humidity alarm.

Eveytime I set the correct value, they unset after a while and the alarm is triggered.

 

 

Van: Martin ***@***.***> 
Verzonden: vrijdag 15 december 2023 9:26
Aan: z8i/ha_custom_klimaloggpro ***@***.***>
CC: hifihifi ***@***.***>; Author ***@***.***>
Onderwerp: Re: [z8i/ha_custom_klimaloggpro] ALARM settings in Base station (Issue #5)

 

I just find something about the clock margins... Maybe it is about clock and not low battery... https://github.com/z8i/kloggpro/blob/88a41a42e32140e89db78831977482bfb45b6e8e/kloggpro/klimalogg.py#L2065

**Comment by z8i** [comment]
Yes, you are right. There is something in the code, which sets the humidity alarm, i suspect it does it
* in a situation of low battery (?)
* due to time offset between host and base station (?)

Did you have low battery power in one of the sensors? Or did you see time offset if you compare Klimalogg base station and Home Assistant Time?

**Comment by hifihifi** [comment]
I take out the new battery's on the basestation a few time and no date/time sync with DCF (waited half hour on front of a window). Then I openend the device and cleaned some flux residue on the PCB, not sure if this solves anything. But then it make connection to DCF for time and it worked. Maybe the base station is getting nog in good shape (I think 4 years old?).
I don't get alarms know. Case can be closed.

**Comment by z8i** [comment]
more on alarm settings here https://github.com/z8i/kloggpro/commit/a51718ba97c679aaa101bc39fb086889cea45ce8
